[2024-09-11T03:45:57.410+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T03:45:57.426+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Start_Pipeline01.query_data_from_mongo manual__2024-09-11T03:40:52.435110+00:00 [queued]>
[2024-09-11T03:45:57.437+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Start_Pipeline01.query_data_from_mongo manual__2024-09-11T03:40:52.435110+00:00 [queued]>
[2024-09-11T03:45:57.438+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-09-11T03:45:57.458+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): query_data_from_mongo> on 2024-09-11 03:40:52.435110+00:00
[2024-09-11T03:45:57.470+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4457) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T03:45:57.471+0000] {standard_task_runner.py:72} INFO - Started process 4458 to run task
[2024-09-11T03:45:57.469+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Start_Pipeline01', 'query_data_from_mongo', 'manual__2024-09-11T03:40:52.435110+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data-prep-for-model.py', '--cfg-path', '/tmp/tmpf5mofmgc']
[2024-09-11T03:45:57.473+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask query_data_from_mongo
[2024-09-11T03:45:57.539+0000] {task_command.py:467} INFO - Running <TaskInstance: Start_Pipeline01.query_data_from_mongo manual__2024-09-11T03:40:52.435110+00:00 [running]> on host dca6f81c3bd4
[2024-09-11T03:45:57.663+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Start_Pipeline01' AIRFLOW_CTX_TASK_ID='query_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T03:40:52.435110+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T03:40:52.435110+00:00'
[2024-09-11T03:45:57.665+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T03:45:57.724+0000] {transport.py:1923} INFO - Connected (version 2.0, client OpenSSH_8.2p1)
[2024-09-11T03:45:57.777+0000] {transport.py:1923} INFO - Authentication (password) successful!
[2024-09-11T03:46:01.235+0000] {python.py:240} INFO - Done. Returned value was: /opt/***/data/mongo_data.json
[2024-09-11T03:46:01.252+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T03:46:01.253+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Start_Pipeline01, task_id=query_data_from_mongo, run_id=manual__2024-09-11T03:40:52.435110+00:00, execution_date=20240911T034052, start_date=20240911T034557, end_date=20240911T034601
[2024-09-11T03:46:01.301+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-11T03:46:01.315+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T03:46:01.317+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
